hide_download: true
hide_download_original: null
leftnav:
- identifier: ced402c8-829e-0b25-a86f-2cb7e48bc36e
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 4d6c0ed9-49e1-c8c7-f424-c37a7a5d7ddc
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 996854ee-3cbf-9907-aa0f-f3c76730fcf7
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: df63b8d7-3fad-cc76-2f8d-de6a3094c994
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 1864e8a5-06c4-55e1-7cb9-93915b8161d6
  name: Disclaimer
  pageRef: /pages/instructor-s-preface
  weight: 50
